#server:
#  port: 8888

#jimi:
#  cloud:
#    whiteList:
#      - 2046651

app:
  id: spring-cloud-gateway
  # set apollo meta server address, adjust to actual address if necessary
apollo:
  meta: http://apollo-config.dev.jimiops.top

#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: new-tsp
#          uri: http://172.26.20.116:8280
#          predicates:
#            - Path=/tsp/**
#            - name: MyReadBodyPredicateFactory
#          filters:
#            - StripPrefix=1
#        - id: old-user
#          uri: http://172.26.20.116:8281
#          predicates:
#            - Path=/tsp/**
#          filters:
#            - StripPrefix=1
#        - id: route1
#            uri: http://172.26.20.116:8280
#            predicates:
#              - Path=/tsp/**
#            filters:
#              - StripPrefix=1
#        - id: test_route
#          uri: https://hk-test.tracksolidpro.com
#          predicates:
#            - name: MyReadBodyPredicateFactory
#            - Path=/gateway
#            - Weight=group1, 5
#          filters:
#            - StripPrefix=1
#        - id: route2
#          uri: https://eu-test.tracksolidpro.com/
#          predicates:
#            - Path=/gateway/**
#            - Weight=group1, 5
#            - name: MyReadBodyPredicateFactory
#          filters:
#            - StripPrefix=1

# 访问路径：localhost:88/hello?url=baidu 代表跳转到www.baidu.com/hello
# url带有baidu的自动跳转到https://www.baidu.com
# - Query=url,baidu
#  StripPrefix=1，表示去掉前缀，去掉1个前缀