spring:
  application:
    name: graphql-test
  data:
    mongodb:
      host: dds-bp141a219e43f5f42256.mongodb.rds.aliyuncs.com
      port: '3717'
      username: smart
      password: smart
      database: smart
      connectTimeout: '0'
      maxWaitTime: '180000'
      connectionsPerHost: '1000'
      socketTimeout: '0'

graphql:
  servlet:
    mapping: /graphql
    enabled: true
  tools:
    schema-location-pattern: "**/*.graphqls"
graphiql:
  mapping: /graphiql
  endpoint:
    graphql: /graphql
  subscriptions:
    timeout: 30
    reconnect: false
  enabled: true
