server:
  port: 8004

spring:
  rabbitmq:
    host: 192.168.59.20
    port: 5672
    username: mml
    password: 123456
    virtual-host: /
    publisher-confirms: true  #  消息发送到交换机确认机制,是否确认回调
    publisher-returns: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource   #这里是配置druid连接池，以下都是druid的配置信息
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

logging:
  file: rabbitmq-service.log
  level:
    com.rabbitmq: debug